piVersion: v1
kind: Service
metadata:
  name: jenkins-service
  namepsace: jenkins
spec:
  selector:
    app: nginx 
  type: NordPort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      NordPort: 3000
